services:
  db:
    # to fix SCRAM authentication error
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=pw1
      - POSTGRES_DB=ergtrack
    # volumes:
      # - db:/var/lib/postgresql/data

  api:
    build: . #find dockerfile in this dir and build docker image
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DEV_ENV=docker_compose
      - GOOGLE_APPLICATION_CREDENTIALS=/ergtrack23api/secret/cloud_storage_access_sa_key.json
    command: sh -c "python init_db.py && tail -F non-existent-file-to-cause-infinite-loop"
    # command: sh -c "python init_db.py && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./:/ergtrack23api

volumes:
  db:
    driver: local